(TeX-add-style-hook "convolution"
 (lambda ()
    (LaTeX-add-index-entries
     "domains"
     "time domain"
     "frequency domain"
     "domain!time"
     "domain!frequency"
     "z-transform!of an impulse"
     "unit impulse"
     "z-transform!of an exponential"
     "geometric series"
     "geometric series!common ratio"
     "geometric series!as function of first term"
     "unit step"
     "z-transform!of a unit step"
     "convolution!discrete!definition"
     "convolution!commutative property"
     "convolution!distributive property"
     "convolution!associative property"
     "convolution!discrete!implementation"
     "C code!convolution|("
     "C code!convolution|)"
     "convolution!kernel"
     "convolution!boundary conditions"
     "MATLAB code!convolution"
     "z-transform!properties of"
     "z-transform!relation to $z$ operator"
     "z-transform!and delay"
     "z-transform!of a time-shifted impulse"
     "z-transform!computing convolution with"
     "filter!impulse response"
     "z-transform!relationship to filter transfer function"
     "filter!transfer function!relationship to its z-transform"
     "filter!transfer function!determining with z-transform")
    (LaTeX-add-labels
     "ch:convolution"
     "tb:zt-transforms"
     "eq:zt"
     "eq:zt-delta"
     "eq:zt-expof"
     "eq:exp-zt"
     "eq:zt-expoF"
     "fig:zt-expo-r0.5f"
     "fig:zt-expo-r0.5F"
     "fig:zt-expo-r1F"
     "eq:zt-expo-cF"
     "sc:convolution"
     "eq:convolution"
     "eq:zt-conv"
     "eq:zt-conv-exp"
     "alg:convolution"
     "fg:convex"
     "fig:zt-conv-etet"
     "tb:zt-property"
     "eq:zt-hx"
     "eq:zt-HX")))

