(TeX-add-style-hook "fft"
 (lambda ()
    (LaTeX-add-index-entries
     "Fourier Transform|emph"
     "Fourier Transform!of a pulse"
     "Discrete Fourier Transform (DFT)"
     "Discrete Fourier Transform (DFT)!properties of"
     "FFT!points"
     "Discrete Fourier Transform (DFT)!of an exponential"
     "geometric series!common ratio"
     "Discrete Fourier Transform (DFT)!direct computation"
     "Discrete Fourier Transform (DFT)!direct computation!complexity"
     "Discrete Fourier Transform (DFT)!FFT"
     "Discrete Fourier Transform (DFT)!of sum of two sinusoids"
     "FFT!of finite-duration signals|("
     "FFT!rectangular window and"
     "FFT!of finite-duration signals|)"
     "FFT!frequency resolution"
     "FFT!of time-varying signals"
     "FFT!time/frequency tradeoff"
     "spectrogram|emph"
     "Fourier transform!short-time|emph"
     "spectrogram!of a bird call"
     "FFT!Hamming window and"
     "FFT!Bartlett window and")
    (LaTeX-add-labels
     "ch:fft"
     "sc:fourier-xform"
     "eq:ft-x"
     "eq:ft-X"
     "fig:ft-pulse-x"
     "fig:ft-pulse-X"
     "eq:ft-pulse-X"
     "fig:ft-pulse-xX"
     "eq:dft"
     "eq:idft"
     "eq:fs-ckrepeat"
     "eq:dft-w"
     "tb:delta-f"
     "eq:dft-2idft1"
     "eq:dft8-freqs"
     "fig:dft-exp-xX"
     "eq:exp-dft1"
     "fig:dft-exp-X2"
     "sc:fft"
     "eq:fft-xexo"
     "eq:fft-repeat-even"
     "eq:fft-repeat-odd"
     "eq:2fft-even"
     "eq:2fft-odd"
     "alg:fft-recursive"
     "tb:fft-bitrevers"
     "alg:fft"
     "fg:fft-iterative"
     "fig:fft-sin-xX"
     "fig:fft-leakage"
     "eq:usefft-Y1"
     "eq:usefft-rWk1"
     "eq:usefft-rWk2"
     "fig:usefft-rWX1"
     "fig:usefft-rWinfX"
     "eq:usefft-rWkinf"
     "eq:usefft-cos3a"
     "eq:usefft-cos3"
     "fig:usefft-rWX3-1"
     "fig:usefft-rWX3-2"
     "fig:ufft-birdspg-c1"
     "fig:ufft-birdspg-c2"
     "fig:ufft-birdspg-b1"
     "fig:ufft-birdspg-b2"
     "fig:ufft-hmw"
     "eq:ufft-hnw"
     "fig:ufft-baw"
     "eq:ufft-gw"
     "fig:ufft-hnrt-cosx"
     "fig:ufft-bart-cosx"
     "fig:ufft-hnba-cosx"
     "fig:ufft-birdspg-c3"
     "fig:ufft-birdspg-b3"
     "it:64")))

