(TeX-add-style-hook "computer-signals"
 (lambda ()
    (LaTeX-add-index-entries
     "data acquisition"
     "transduction"
     "analog-to-digital conversion|("
     "digitization|see{analog-to-digital conversion}"
     "analog-to-digital conversion!sampling|("
     "Nyquist limit|see{analog-to-digital conversion, aliasing}"
     "analog-to-digital conversion!aliasing|("
     "analog-to-digital conversion!aliasing|)"
     "analog-to-digital conversion!sampling|)"
     "analog-to-digital conversion!quantization|("
     "analog-to-digital conversion!quantization!noise|("
     "signal-to-noise ratio (SNR)"
     "decibel"
     "analog-to-digital conversion!quantization!noise|)"
     "MATLAB code!quantization"
     "audio files!bird calls"
     "analog-to-digital conversion!quantization|)"
     "analog-to-digital conversion!dynamic range|("
     "perception!auditory!psychophysics"
     "companding"
     "analog-to-digital conversion!dynamic range|)"
     "analog-to-digital conversion|)")
    (LaTeX-add-labels
     "ch:computer-signals"
     "fg:adc"
     "fg:sampled2k"
     "fg:sampled300"
     "eq:samp-phasor"
     "eq:samp-phasor2"
     "eq:set-ambig-freq"
     "eq:neg-freq"
     "fg:quant2k"
     "eq:var"
     "eq:fseries"
     "eq:fint"
     "it:sq-wave-spectrum"
     "it:aliased-sq-wave")))

