(TeX-add-style-hook "filt-intro"
 (lambda ()
    (LaTeX-add-index-entries
     "filter!bandpass"
     "filter!low pass"
     "filter!high pass"
     "filter!band stop"
     "audio files!sinusoids"
     "audio
  files!filtering"
     "block diagram"
     "diagram!block"
     "data flow diagram"
     "diagram!data flow"
     "flow chart"
     "diagram!flow chart"
     "filter!frequency response|emph"
     "frequency response"
     "magnitude response"
     "phase response"
     "filter!digital"
     "sampling period"
     "sampling rate"
     "Nyquist limit"
     "defining equation"
     "equation!defining"
     "z@$z$!delay operator"
     "operator!mathematical|("
     "operator!delay"
     "operator!mathematical|)"
     "filter!transfer function|emph"
     "operator!transfer function"
     "z@$z$!complex plane"
     "zero"
     "frequency response!zero"
     "polynomial!order two!roots of"
     "quadratic equation!roots of"
     "filter!phase response|(emph"
     "filter!phase response|)"
     "decibel"
     "trigonometry!double-angle formulae"
     "MATLAB code!digital filtering|("
     "MATLAB code!digital filtering|)")
    (LaTeX-add-labels
     "ch:filt-intro"
     "eq:sine4"
     "fig:sine4"
     "fig:sine4-band"
     "fig:sine4-f2"
     "fig:sine4-sp"
     "fig:ff-bdiag"
     "eq:ff-filt-gen"
     "eq:ff-filt-ph"
     "eq:fresp-mult"
     "eq:fresp-polar"
     "eq:ff-mha"
     "eq:ff-mh"
     "eq:digital-tau"
     "eq:ff-manyk"
     "eq:one-delay"
     "fig:ff-blacbox"
     "sc:ste-oper"
     "eq:ff-simplez"
     "eq:twostep-ex"
     "eq:twostep-ex-magresp"
     "eq:ff-z0s"
     "eq:twostep-factored"
     "fig:ff-exp2zs90"
     "fig:ff-exp2zs150"
     "fig:ff-exp2zh90"
     "fig:ff-exp2zh150"
     "eq:ff-zero"
     "eq:compute-phase-resp"
     "eq:ff-2ztho"
     "eq:ff-exph1"
     "eq:ff-expph1"
     "eq:ff-expph2"
     "eq:ff-2zth"
     "eq:ff-2zt"
     "fig:ff-exp2zh90-r1"
     "fig:ff-exp2zp90-r1"
     "fig:ff-expsin2_sp"
     "fig:ff-expsin2")))

