(TeX-add-style-hook "fb-filters"
 (lambda ()
    (LaTeX-add-index-entries
     "filter!poles|emph"
     "partial fraction expansion"
     "filter!parallel one-pole"
     "filter!resonance"
     "bandwidth"
     "filter!cutoff amplitude"
     "filter!cutoff frequency"
     "filter!passband"
     "MATLAB code!numerical error|("
     "MATLAB code!numerical error|)"
     "filter!cascade")
    (LaTeX-add-labels
     "ch:fb-filters"
     "fig:fb-bdiag"
     "eq:fb-1p"
     "eq:fb-ff"
     "eq:fb-xfer"
     "eq:fb-1pmh"
     "fig:fb-exp1pc90"
     "fig:fb-exp1ph90r2"
     "eq:fb-exxfer"
     "eq:fb-eximp"
     "eq:fb-1pexp"
     "fig:fb-nterm-bdiag"
     "eq:manypoles"
     "eq:mp-denomprod"
     "eq:fb-band"
     "fig:fb-exp1pc0_phi"
     "eq:reson-inv-mag2"
     "eq:fb-band2a"
     "eq:fb-band2b"
     "eq:calc-bw"
     "eq:gen-xfer"
     "eq:gen-impl"
     "eq:series-direct"
     "eq:series-twoterms")))

