(TeX-add-style-hook "physical-signals"
 (lambda ()
    (LaTeX-add-index-entries
     "perception!visual|("
     "perception!visual!color constancy"
     "perception!visual!cone"
     "perception!visual!luminance"
     "perception!visual!photoreceptor"
     "perception!visual!retina"
     "perception!visual!rod"
     "perception!visual!trichromatic"
     "perception!as a construct"
     "perception!visual!visible light"
     "visible light"
     "spectrum!visible"
     "spectrum!electromagnetic"
     "perception!visual!color|("
     "perception!visual!color|)"
     "perception!visual|)"
     "perception!auditory|("
     "perception!auditory|)"
     "perception!multimodal fusion"
     "CRT|("
     "LCD"
     "CRT!electron gun|("
     "CRT!cathode"
     "CRT!cathode rays"
     "CRT!anode"
     "CRT!electron gun|)"
     "CRT!phosphor"
     "CRT!raster scanning|("
     "CRT!raster scanning!non-interlaced"
     "CRT!raster scanning!interlaced"
     "CRT!raster scanning|)"
     "CRT!color|("
     "CRT!color|)"
     "CRT|)"
     "multimedia systems!basic functions|("
     "multimedia systems!computing requirements"
     "multimedia systems!basic functions|)"
     "tuning fork|("
     "differential equations"
     "tuning fork|)"
     "phase!of a sinusoid"
     "complex numbers|(emph"
     "j ($\\sqrt{-1}$)"
     "i|see{j}"
     "complex numbers!rectangular form"
     "complex numbers!polar form"
     "complex numbers!magnitude|see{complex numbers, polar form}"
     "complex numbers!angle|see{complex numbers, polar form}"
     "complex numbers|)"
     "Euler's formula|emph"
     "MATLAB code!beating"
     "audio files!beating"
     "sound files|see{audio files}"
     "frequency!angular"
     "$\\omega$"
     "frequency!Hertz (Hz)"
     "period!of a sinusoid"
     "harmonics"
     "sinusoids!orthogonal"
     "sinusoids!independent"
     "orthogonality"
     "independence"
     "DC component"
     "frequency!fundamental"
     "Fourier series|emph"
     "spectrum"
     "frequency analysis"
     "spectral analysis"
     "vectors|("
     "vectors!basis"
     "vectors!projection"
     "vectors!components"
     "vectors!as sum of components"
     "vectors!inner product"
     "vectors!sum"
     "vectors!inner product!distributive property"
     "vectors!inner product!commutative property"
     "vectors!orthogonal"
     "vectors!unit"
     "unit vector"
     "vectors|)"
     "Fourier Series|emph"
     "Fourier coefficients|emph"
     "l'H\\^{o}pital's rule"
     "complex sinusoids!as an orthogonal basis"
     "power spectrum"
     "Fourier Series!of a square wave"
     "sinc function")
    (LaTeX-add-labels
     "ch:physical-signals"
     "fg:crt"
     "fg:raster"
     "fg:tuningfork"
     "eq:tuningfork"
     "eq:gensine"
     "fg:phasor-components"
     "fg:vector-sum"
     "eq:cmplx-sin-rect"
     "eq:cmplx-sin-ddt"
     "eq:cmplx-sin"
     "eq:pow-rot"
     "eq:phasor-first"
     "fg:beating"
     "fg:beating-waveform"
     "eq:sum-harmonics"
     "eq:basis-proj"
     "eq:vec-comps"
     "eq:inner-product"
     "eq:complex-ip"
     "eq:func-ip"
     "eq:vec-sum"
     "eq:ip-dist"
     "eq:ip-commut"
     "eq:orthogonal"
     "eq:unit-vector"
     "eq:fs"
     "eq:fs-ck"
     "eq:fs-ck2"
     "eq:fs1"
     "eq:orth-sines"
     "eq:fs-cs3"
     "eq:real-f-pspec"
     "eq:fs-freal1"
     "eq:fs-freal2"
     "fig:fs-pulse"
     "eq:sq-fs1"
     "eq:sq-fs2"
     "eq:sq-fs3"
     "eq:fs-pul-cn1"
     "eq:fs-pul-cn2"
     "eq:fs-Snpi"
     "eq:fs-S0"
     "fig:sinc"
     "eq:fs-pulsef1"
     "eq:fs-pulsef2"
     "eq:fs-pulsef"
     "fig:fs-pulsef"
     "fig:fs-pulsef2"
     "eq:fs-pulseabscn"
     "fig:fs-pulsecn"
     "fig:fs-pulsecntau"
     "fig:fs-pulsecnT")))

