(TeX-add-style-hook "compression"
 (lambda ()
    (LaTeX-add-index-entries
     "Shannon"
     "information theory"
     "compression!information theory and"
     "entropy"
     "compression!lossless|emph"
     "compression!lossy|emph"
     "compression!quantization and"
     "compression!lossless|("
     "compression!run-length"
     "Huffman coding|("
     "compression!Huffman|("
     "compression!arithmetic"
     "arithmetic coding"
     "compression!Huffman|)"
     "Huffman coding|)"
     "compression!dictionary based"
     "compression!lossless|)"
     "compression!lossy|("
     "compression!human perception and"
     "compression!pulse code modulation (PCM)"
     "pulse code modulation (PCM)"
     "differential pulse code modulation"
     "compression!delta modulation"
     "delta modulation"
     "ADPCM"
     "compression!temporal redundancy and"
     "compression!spatial redundancy and"
     "discrete cosine transform (DCT)"
     "compression!lossy|)")
    (LaTeX-add-labels
     "ch:compression"
     "fg:shannon"
     "fg:taxonomy"
     "fg:encoding"
     "tb:prefix"
     "fg:code-tree")))

